# Этап 1: билд и установка зависимостей
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

ENV UV_PROJECT_ENVIRONMENT=system

WORKDIR /opt/app

COPY pyproject.toml uv.lock ./

RUN uv sync --locked

COPY . .

ENV PATH="/app/.venv/bin:${PATH}"

CMD ["uv", "run", "./cmd/app"]
