FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --no-dev --no-cache

FROM python:3.13-slim-bookworm
WORKDIR /app

ENV PATH="/app/.venv/bin:${PATH}"

COPY --from=builder --chown=app:app /app .

COPY . .

CMD ["./scripts/start.sh"]
