services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    env_file:
      - ../config/.env.local
    volumes:
      - ../cli:/app/cli
      - ../internal:/app/internal
      - ../tests:/app/tests
      - ../log:/app/log
    restart: unless-stopped
