services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    env_file:
      - ../config/.env.local
    volumes:
      - ../cli:/app/cli
      - ../internal:/app/internal
      - ../tests:/app/tests
      - ../log:/app/log
      - ../migrations:/app/migrations
      - ../pyproject.toml:/app/pyproject.toml
      - ../scripts:/app/scripts
      - ../data/ml:/app/data/ml
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      kafka:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    volumes:
      - ../data/postgresql_data:/var/lib/postgresql/data
    env_file:
      - ../config/.env.local
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopass
    volumes:
      - ../data/minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://127.0.0.1:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  zookeeper:
    image: bitnami/zookeeper:3.9.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/0.0.0.0/2181'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BITNAMI_DEBUG=yes
    volumes:
      - ../data/kafka_data:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/0.0.0.0/9092'" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgresql_data:
  kafka_data:
  minio_data:
