services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ../config/.env.local
    runtime: nvidia
    restart: unless-stopped
