services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    env_file:
      - ../config/.env.local
    volumes:
      - ../cli:/app/cli
      - ../internal:/app/internal
      - ../tests:/app/tests
      - ../log:/app/log
      - ../migrations:/app/migrations
      - ../pyproject.toml:/app/pyproject.toml
      - ../scripts:/app/scripts
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    volumes:
      - ../data/postgresql_data:/var/lib/postgresql/data
    env_file:
      - ../config/.env.local
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    env_file:
      - ../config/.env.local
    volumes:
      - ../data/minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://127.0.0.1:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgresql_data:
