"""update: add columnt to models is_exists

Revision ID: 3fa99d7262b3
Revises: fe7f16435759
Create Date: 2025-05-24 07:10:35.687857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa99d7262b3'
down_revision: Union[str, None] = 'fe7f16435759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('is_exsixts', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'is_exsixts')
    # ### end Alembic commands ###
