"""init db

Revision ID: 55f06c12e1a3
Revises:
Create Date: 2025-05-09 20:20:05.071991

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "55f06c12e1a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
