"""feat: add tasks model

Revision ID: b2667b3dfc7b
Revises: 327100d5b326
Create Date: 2025-05-19 20:06:32.419072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2667b3dfc7b"
down_revision: str | None = "327100d5b326"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tasks",
    sa.Column("file_id", sa.UUID(), nullable=True),
    sa.Column("user_id", sa.UUID(), nullable=True),
    sa.Column("predict_id", sa.UUID(), nullable=True),
    sa.Column("message", sa.String(), nullable=True),
    sa.Column("status", sa.String(length=256), nullable=False),
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("created_on", sa.DateTime(), nullable=True),
    sa.Column("updated_on", sa.DateTime(), nullable=True),
    sa.Column("deleted_on", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["file_id"], ["files.id"] ),
    sa.ForeignKeyConstraint(["predict_id"], ["predicts.id"] ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
