"""fix: files fk

Revision ID: dea0a82af034
Revises: e39acba5c693
Create Date: 2025-05-27 06:52:42.213414

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dea0a82af034"
down_revision: str | None = "e39acba5c693"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("predicts_file_id_fkey", "predicts", type_="foreignkey")
    op.create_foreign_key(None, "predicts", "files", ["file_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "predicts", type_="foreignkey")
    op.create_foreign_key("predicts_file_id_fkey", "predicts", "user", ["file_id"], ["id"])
    # ### end Alembic commands ###
