"""update naming

Revision ID: e39acba5c693
Revises: 3fa99d7262b3
Create Date: 2025-05-24 10:09:16.886788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e39acba5c693"
down_revision: str | None = "3fa99d7262b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("is_exists", sa.Boolean(), nullable=False))
    op.drop_column("models", "is_exsixts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("is_exsixts", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("models", "is_exists")
    # ### end Alembic commands ###
