"""update: change to default message

Revision ID: fe7f16435759
Revises: b2667b3dfc7b
Create Date: 2025-05-19 20:46:39.452388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7f16435759'
down_revision: Union[str, None] = 'b2667b3dfc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
